
title: Ninad Jangle
logo: "/images/logo.jpeg" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  3rd year Electronics Engineering student at Veermata Jijabai Technological Institute, Silicon enthusiast, Proficient in Circuit Design, RISC-V and Automation.
  <br>
  <b>Gsoc 21’ @FOSSi Foundation | 2nd Prize @7th Delta Advanced Automation Cup | Electronics Head @SRA VJTI  </b>
  <br><br>
  <a href="https://www.linkedin.com/in/ninadjangle//">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://ninadjangle.tech/pdf/NinadJangleResume.pdf">View My CV</a> 
  <br><br>
  <a href="https://github.com/ninja3011">View My GitHub Profile</a> 
  
  <br><br>  <br><br>

 
theme: jekyll-theme-minimal
