
title: Ninad Jangle
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Electronics Enthusiasts. I'm proficient in circuit and PCB designing. I have a great interest in fields like FPGA, Digital VLSI, Computer Architecture.  
  <br>
  <b>Gsoc 21’ @FOSSi Foundation | 2nd Prize @7th Delta Advanced Automation Cup | SRA VJTI 3rd year Electronics Engineering student at Veermata Jijabai Technological Institute Silicon enthusiast, Proficient in Circuit Design and Automation. </b>
  <br><br>
  <a href="https://www.linkedin.com/in/ninadjangle//">View My LinkedIn Profile</a> 


 
theme: jekyll-theme-minimal
